**Passo a passo:**

In [ ]:
#Lógica de programação:

#Passo 0 - Entender o desafio que você quer resolver

#Passo 1 - Percorrer todos os arquivos de pasta base de dados (Pasta Vendas)
import os
import pandas as pd

lista_arquivos = os.listdir("/content/drive/MyDrive/Curso basico de python/Vendas/Vendas") #lista todos os arquivos q estao no diretorio
display(lista_arquivos)

In [ ]:
tabela_total = pd.DataFrame()

#Passo 2 - Importar as bases de dados de vendas
for arquivo in lista_arquivos:
  #se tem "Vendas no nome do arquivo, então"
  if "Vendas" in arquivo:
    #importar o arquivo
    tabela = pd.read_csv(f"/content/drive/MyDrive/Curso basico de python/Vendas/Vendas/{arquivo}")
    tabela_total = tabela_total.append(tabela) #append = adicionar
    
#Passo 3 - Tratar/Compilar as bases de dados
display(tabela_total)

     Unnamed: 0     SKU     Produto  ...          Loja Preco Unitario Unnamed: 8
0            13  HL4379   Televisão  ...         Goiás           2500        NaN
1            19  HL9962     Android  ...         Goiás           3400        NaN
2            45  HL1918      iPhone  ...         Goiás           5300        NaN
3            50  HL7348  SmartWatch  ...         Goiás           1400        NaN
4            97  HL7348  SmartWatch  ...         Goiás           1400        NaN
..          ...     ...         ...  ...           ...            ...        ...
699        9947  HL1918      iPhone  ...  Porto Alegre           5300        NaN
700        9980  HL1918      iPhone  ...  Porto Alegre           5300        NaN
701        9983  HL2714      Tablet  ...  Porto Alegre           1600        NaN
702        9993  HL1148      Câmera  ...  Porto Alegre           2100        NaN
703        9997  HL1918      iPhone  ...  Porto Alegre           5300        NaN

[9999 rows x 10 columns]

In [ ]:
# Passo 4 - Calcular o produto mais vendido (em quantidade)
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida"]].sort_values(by="Quantidade Vendida", ascending=False) 
#sort_values() = organiza os valores, ascending=True : Forma crescente, ascending=False : Forma decrescente
display(tabela_produtos)

            Quantidade Vendida
Produto
iPhone                    8974
Televisão                 5931
Notebook                  3249
Android                   3183
SmartWatch                2980
Tablet                    2921
Câmera                    2805

In [ ]:
# Passo 5 - Calcular o produto que mais faturou (em faturamento)
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']

tabela_faturamento = tabela_total.groupby("Produto")
tabela_faturamento = tabela_faturamento[["Faturamento"]].sum().sort_values(by="Faturamento", ascending=False) 
display(tabela_faturamento)

            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000

In [ ]:
# Passo 6 - Calcular a loja/cidade que mais vendeu (em faturamento) 
tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[["Faturamento"]].sort_values(by="Faturamento", ascending=False)
display(tabela_lojas)

                Faturamento
Loja
São Paulo          22098300
Rio de Janeiro     14867800
Fortaleza          14087900
Salvador           13111300
Goiás               7441800
Recife              7303000
Curitiba            7060500
Porto Alegre        6868600
Belo Horizonte      6480300

In [ ]:
# Passo 7 - Criar um gráfico/dashboard da loja/cidade que mais vendeu
import plotly.express as px
grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y="Faturamento")
#É tabela_lojas.index e não "Loja" pq a loja é um indice eo faturamento nao
grafico.show()